config/routes.rb
Rails.application.routes.draw do
  get 'sessions/signup'

  devise_for :landlords, controllers: { registrations: 'landlord/registrations' }
  devise_for :users, controllers: { registrations: 'tenant/registrations' }

  get '/signup' => 'sessions#signup'
  get '/dashboard' => 'dashboards#show'
  get '/pay_rent' => 'dashboards#pay'
  post '/add_account' => 'dashboards#create'
  post '/charge' => 'dashboards#charge'
  root 'pages#home'

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||
     if resource.is_a?(User)
       dashboard_url
     else
       super
     end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :charge]
  def show
  end

  def pay
  end

  def create
    exchangeTokenResponse = Plaid.exchange_token(params[:public_token], params[:account_id])
    current_user.update(stripe_bank_account_token: exchangeTokenResponse.stripe_bank_account_token)
    user = Plaid.set_user(exchangeTokenResponse.access_token, ['auth'])
    user.get('auth')
    user.accounts.each { |account| print account.meta['name'] + "\n"}
    redirect_to dashboard_url
  end

  def charge
    account = Stripe::Account.create(
      {
        :country => "US",
        :managed => true
      }
    )
    p account
    redirect_to dashboard_url
          # Amount in cents
    # @amount = params[:amount]
    #
    # customer = Stripe::Customer.create(
    #   :email => params[:stripeEmail],
    #   :source  => current_user.stripe_bank_account_token
    # )
    #
    # charge = Stripe::Charge.create(
    #   :customer    => customer.id,
    #   :amount      => @amount,
    #   :description => 'Rails Stripe customer',
    #   :currency    => 'usd'
    # )
    # redirect_to dashboard_url
    # rescue Stripe::CardError => e
    #   flash[:error] = e.message
    #   redirect_to dashboard_url
  end
end

app/controllers/landlord/registrations_controller.rb
class Landlord::RegistrationsController < Devise::RegistrationsController
  def create
    # Stripe.api_key = PLATFORM_SECRET_KEY
    Stripe::Account.create(
      {
        :country => "US",
        :managed => true
      }
    )
    super
  end
  private

  def sign_up_params
    params.require(:landlord).permit(:first_name, :last_name, :email, :password, :password_confirmation, :business_type, :date_of_birth, :ssn, :address)
  end

  def account_update_params
    params.require(:landlord).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:landlord).permit(:first_name, :last_name, :email, :password, :password_confirmation, :business_type, :date_of_birth, :ssn, :address)
  end

  def account_update_params
    params.require(:landlord).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signup
  end
end

app/controllers/tenant/registrations_controller.rb
class Tenant::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboards/pay.html.erb
  Please read below. If you agree and would like to proceed the payment process, please check the box below.
<form>
  <input id='authorization' type='checkbox'/>
  I authorize Rent to electronically debit my account and, if necessary, electronically credit my account to correct erroneous debits.
</form>
<div class='row'>
  <div class='col-md-6'>
    <div class='method' id='linkButton'>
      <%= link_to 'Instant Verification', '#' %>
      <p>You can authenticate directly with your bank in real-time—no digging around for routing numbers.
        (This process also prevents most of the common errors of mistyping bank account numbers or incorrect routing numbers.)</p>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='method'>
      <%= link_to 'Delayed Verification (Micro-deposits)', '#' %>
      <p>With micro-deposits, we send two unique amounts to your bank account
        so that you can verify their account by entering the amounts you see on your statement.</p>
    </div>
  </div>
  <!-- <form id='payment-form' action='/add_account' method='post'>
    <input type='hidden' value='<%= form_authenticity_token %>' name='authenticity_token'>
    <input type='hidden' name='public_token' id='public_token'>
    <input type='hidden' name='account_id' id='account_id'>
    <input type='submit' value='Pay Rent'>
  </form> -->
  <form action='/charge' method='post' id='payment_form'>

    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>
    <input type='hidden' value='<%= form_authenticity_token %>' name='authenticity_token'>
    Type:
    <select name='recipient_type' form='payment_form'>
      <option value='individual'>Individual</option>
      <option value='business'>Business</option>
    </select>
    Landlord's Legal Name: <input type='text' placeholder="Jorgen Hahn" name='recipient_name' required/>
    Landlord's bank account: <input type='text' placeholder="1234567890" name='recipient_bank_account' required/>
    Landlord's account routing number: <input type='text' placeholder='123456789' name='recipient_routing_number' required/>
    Amount: $<input type='text' pattern='\d+' name='amount' placeholder="2000"required/>
    <input type='submit'>
  </form>
<div>

<script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
<script>
  $(function() {
    var linkHandler = Plaid.create({
      env: 'tartan',
      clientName: 'Rent',
      key: '<%= ENV['public_key'] %>',
      product: 'auth',
      selectAccount: true,
      onSuccess: function(public_token, metadata) {
        // Send the public_token and account ID to your app server.
        console.log('public_token: ' + public_token);
        console.log('account ID: ' + metadata.account_id);
        // $('#public_token').val(public_token);
        // $('#account_id').val(metadata.account_id);
        $.post('/add_account', { public_token: public_token, account_id: metadata.account_id })
      }
    });
  // Trigger the Link UI
    $('#authorization').change(function() {
      if (this.checked) {
        document.getElementById('linkButton').onclick = function() {
          linkHandler.open();
        };
      }
    })
  })

</script>

app/views/dashboards/show.html.erb
<h1>DashBoard</h1>

<%= link_to 'Pay Rent', pay_rent_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container'>
  <nav>
    <ul>
      <% if user_signed_in? || landlord_signed_in? %>
        <% if user_signed_in? %>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% end %>
        <% if landlord_signed_in? %>
          <li><%= link_to 'Sign out', destroy_landlord_session_path, method: :delete %></li>
        <% end %>
      <% else %>
        <li><%= link_to 'Sign up', signup_path %></li>
        <li><%= link_to 'Log in', new_user_session_path %></li>
      <% end %>
    </ul>

  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pay rent online!</h1>
<p>Easy way to pay rent</p>